" let g:indentLine_enabled = 1
" let g:indentLine_setColors = 0
let g:indentLine_char = '│'
let g:indentLine_bgcolor_term = 202
let g:indentLine_color_term = 239
" let g:indentLine_setConceal = 0
let g:vim_json_syntax_conceal = 0
" let g:indentLine_concealcursor = 'inc'
" let g:indentLine_conceallevel = 2
